### PR TITLE
Feature/poi service

### PR DESCRIPTION
**Pull request by GoldJns**
Merging poi service

### CODE REVIEW

**Comment by GoldJns** [comment]
@amza94 good solution service works like expected. One suggestion from me: How about using springs `@Service` annotation?. It is considered bad practice to access the poi respository in the controller. What do you think?

**Review by wong030 — APPROVED** [review]

**Comment by GoldJns** [comment]
Marked as draft for now... will be merged after user service and when the service annotation is implemented here

**Review by amza94 — APPROVED** [review]
Poiservice Service Class added with @service Annotation contens Funktion for Poi Controller Class

**Comment by GoldJns** [comment]
@amza94 Looks good in general,  some improvements  from my side:  class Poiservice to `PoiService`(classes in general should be Pascal case) and the object of PoiService should be named poiService (camel case). It seems like there are merge conflicts, try merging origin/main into feature/poi-service branch and resolve conflicts locally, Afterwards push changes and the conflicts should be gone. @Zohaib770 please review the pr after the changes

**Comment by GoldJns** [comment]
I resolved remaining conflicts... Pois are visible. @Zohaib770  please review and test the current state (look if pois are visible on map)

**Review by Zohaib770 — APPROVED** [review]
now it's better

**Pull request merged**
